"""empty message

Revision ID: 013cc6afd436
Revises: 8c22897bf4b1
Create Date: 2025-01-22 19:08:42.130450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013cc6afd436'
down_revision = '8c22897bf4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
