"""empty message

Revision ID: 87f18113e144
Revises: cfda833988e1
Create Date: 2025-01-24 18:33:09.452439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f18113e144'
down_revision = 'cfda833988e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_homeworld_id_fkey', 'planet', ['homeworld_id'], ['id'])

    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    # ### end Alembic commands ###
